/* eslint-disable */
// Generated by Wrangler by running `wrangler types --strict-vars false --include-runtime false` (hash: 9123ce6e2793f05fcad31c528336af47)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		DEBUG: string;
		GITHUB_TOKEN: string;
		SENTRY_DSN: string;
	}
}
interface Env extends Cloudflare.Env {}
