name = "coverage-badge"
account_id = "d6252a570c309c113744c9e11317e271"
workers_dev = true
compatibility_date = "2024-09-23"
main = "./src/index.ts"
placement = { mode = "smart" }

[[kv_namespaces]]
binding = "COVERAGE_CACHE"
id = "72ab034048d74a659a9fe51ba10378dc"
preview_id = "f774eb17e121464cb5989ef62fad9060"

[vars]
DEBUG = "FALSE"
